# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: create env file
        run: |
          touch .env
          echo ENGINE_API_KEY=${{ secrets.ENGINE_API_KEY }} >> .env
          echo NODE_ENV: ${{ secrets.NODE_ENV }}
          echo PORT: ${{ secrets.PORT }}
          echo DATABASE: ${{ secrets.DATABASE }}
          echo CLIENT_ID: ${{ secrets.CLIENT_ID }}
          echo DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
